// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABTVJQMMxAFn2-M4Vl7nBlw5MpbdcAONE',
    appId: '1:554181678051:web:489f4593a060de131846d6',
    messagingSenderId: '554181678051',
    projectId: 'fluttetproject11pplg1',
    authDomain: 'fluttetproject11pplg1.firebaseapp.com',
    storageBucket: 'fluttetproject11pplg1.firebasestorage.app',
    measurementId: 'G-L60M2NS294',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkQPUNrVHMNRHlqSNPfLMsJA35zQWitt4',
    appId: '1:554181678051:android:d3a9174a727f40fe1846d6',
    messagingSenderId: '554181678051',
    projectId: 'fluttetproject11pplg1',
    storageBucket: 'fluttetproject11pplg1.firebasestorage.app',
  );
}
